### ISSUE TITLE
Static Site Generator

### ISSUE THREAD

**Issue by tbeseda** [enhance-dev/enhance-starter-project#19]
It has come up a few times: an Enhance project can probably be rendered as a snapshot to static HTML -- essentially a static site with .html files and a /_public/ static asset folder

I imagine we'd let the web server (Arc Sandbox) do the work. A runner would make a best effort to guess what routes are available, hit the server, and save the output.

I know it's not that simple and might lead to a confusing experience for users. So it should be entirely opt-in and not a part of this package, but an additional install.  
Or even better, maybe there's another tool that can be configured to do this work? Then we could do some experimenting/tuning and make a recommendation to Enhance users.

**Comment by kristoferjoseph** [comment]
I feel like this would be trivial to implement with `@enhance/ssr` but I also feel that users are very well served by many other offerings for static site generation where they are not served at all in the multi-page dynamic space.

I would much rather focus on what makes Enhance awesome than chase the fads in the static site realm.
