### ISSUE TITLE
tiny-json-http package missing

### ISSUE THREAD

**Issue by ablwr** [enhance-dev/enhance-starter-project#21]
Hi! I initially got a dependency error when running this starter project, seeking `tiny-json-http`, using `Node.js v20.0.0
` and then `Node.js v18.16.0`. This is after running `npm install` and `npm start` as instructed.

I'm on Ubuntu 22.04 Jammy Jellyfish and this was a fresh re-install of Node.

I was able to resolve it by installing `tiny-json-http` so no biggie over here but I'm guessing there's a lil something missing somewhere. :innocent: 

Full stacktrace here:
```
node:internal/errors:490
    ErrorCaptureStackTrace(err);
    ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'tiny-json-http' imported from [[redacted by me]]/node_modules/@enhance/arc-plugin-enhance/src/http/any-catchall/[eval1]
    at new NodeError (node:internal/errors:399:5)
    at packageResolve (node:internal/modules/esm/resolve:889:9)
    at moduleResolve (node:internal/modules/esm/resolve:938:20)
    at defaultResolve (node:internal/modules/esm/resolve:1153:11)
    at nextResolve (node:internal/modules/esm/loader:163:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:838:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
    at ESMLoader.import (node:internal/modules/esm/loader:525:22)
    at importModuleDynamically (node:internal/modules/esm/loader:381:29)
    at importModuleDynamicallyCallback (node:internal/process/esm_loader:35:14) {
  code: 'ERR_MODULE_NOT_FOUND'
}
```

**Comment by kristoferjoseph** [comment]
Thank you so much for reporting this issue.
I'm looking into it.

**Comment by kristoferjoseph** [comment]
I am unable to reproduce this following the steps in the quick start.
Can you do me a huge favor and try again following only the instructions listed:
```
npx "@enhance/create@latest" ./testproject -y
cd ./testproject
npm i
npm start
```
And please let me know if this issue persists. 
Thank you kindly.

**Comment by ablwr** [comment]
Works okay now! Maybe something upstream sorted itself out, it happened multiple times yesterday. I'll close this issue, thank you for looking into it!

**Comment by kristoferjoseph** [comment]
Thank you so much for reporting back. 
Very appreciated 🤗

**Comment by ryanblock** [comment]
Sorry, this was indeed a bug that I worked out further upstream. `tiny-json-http` is no longer used in such a way that is necessary for you to retain in your deps, thank you for your patience!

**Comment by ablwr** [comment]
Thanks so much for adding this comment, I appreciate knowing there was a bug there and not just in my brain! :bug:
