### ISSUE TITLE
how to we handle utils js file

### ISSUE THREAD

**Issue by joceqo** [enhance-dev/enhance-starter-project#4]
i guessed that we put common js file in the public folder, but how do we require ( I get require is not defined), is there a way to import ? or even use typescript. Sorry if it is bit of a dumb question

btw the discord link on the doc is outdated

**Comment by kristoferjoseph** [comment]
The public folder is for exposing files for the browser to load so this would not be the place to put files you want to require in node.

You can add a `models/utils` folder to your project and add common js files you want to share there.
