### ISSUE TITLE
Please have offline docs

### ISSUE THREAD

**Issue by jeffgca** [enhance-dev/enhance-starter-project#6]
I looked and couldn't find a repo for the docs site - easiest thing would be cloning that repo and running a local version, but what would be really nice is being able to view the docs in a single page and/or grabbing them as a pdf export. 

( single page would let me print from the browser as a pdf )

Use case: I'm back to travelin' and plan hackin'

**Comment by ryanblock** [comment]
This is a rad idea!

**Comment by jeffgca** [comment]
Workaround:

```
wget \
  --mirror \
  --page-requisites \
  --html-extension \
  --convert-links \
  https://enhance.dev/
```

**Comment by jlooper** [comment]
I'd love to see the docs opensourced, just because they look nice and I'd love to peep the styling. :)

**Comment by kristoferjoseph** [comment]
> I'd love to see the docs opensourced, just because they look nice and I'd love to peep the styling. :)

We are currently cleaning up the docs site to open-source it please stand-by 🙏

**Comment by kristoferjoseph** [comment]
> I looked and couldn't find a repo for the docs site - easiest thing would be cloning that repo and running a local version, but what would be really nice is being able to view the docs in a single page and/or grabbing them as a pdf export.
> 
> ( single page would let me print from the browser as a pdf )
> 
> Use case: I'm back to travelin' and plan hackin'

Absolutely.
I was just looking into what the Dash app would need to suck in Enhance docs.

**Comment by brianleroux** [comment]
docs are now open here! http://github.com/enhance-dev/enhance.dev
